# Generated by Django 5.0.1 on 2024-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
