# Generated by Django 5.0.1 on 2024-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_fecha_fabricacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='modelos',
            field=models.ManyToManyField(to='app.modelo'),
        ),
    ]
