# Generated by Django 5.0.1 on 2024-01-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carrito_total_alter_carrito_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelos',
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disco', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='disipador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disipador', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='fuente_poder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_poder', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gabinete', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='placa_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placa_base', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesador', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='tarjeta_grafica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjeta_grafica', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='version',
            field=models.ManyToManyField(to='app.version'),
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
