# Generated by Django 5.0.1 on 2024-01-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_version_remove_producto_modelos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='version',
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_disco', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='disipador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_disipador', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='fuente_poder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_fuente_poder', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_gabinete', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='placa_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_placa_base', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_procesador', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_ram', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='tarjeta_grafica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_armar_pc_tarjeta_grafica', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='carritoarmarpc',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelos',
            field=models.ManyToManyField(to='app.modelo'),
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
