# Generated by Django 5.0.1 on 2024-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_detalleboleta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='valor_total',
            field=models.IntegerField(),
        ),
    ]
