# Generated by Django 4.2 on 2024-01-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_contacto_tipo_consulta_listadeseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoarmarpc',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
