# Generated by Django 4.2 on 2024-01-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_carritoarmarpc_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='version',
        ),
        migrations.AddField(
            model_name='producto',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.version'),
            preserve_default=False,
        ),
    ]
