# Generated by Django 5.0.1 on 2024-01-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.boleta'),
            preserve_default=False,
        ),
    ]
