# Generated by Django 5.0.1 on 2024-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_pedido_direccion_envio_pedido_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
