# Generated by Django 5.0.1 on 2024-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile_apellido_userprofile_biografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
