# Generated by Django 5.0.1 on 2024-01-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoarmarpc',
            name='equipo_armado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
