# Generated by Django 5.0.1 on 2024-01-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_carritoarmarpc_equipo_armado_tarro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carritoarmarpc',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
